name: Employee Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Employee Laravel Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing

      # Instalação do Laravel
      - uses: ./.github/actions/config-laravel

      # Execução dos testes
      - run: ./vendor/bin/phpunit
